In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
data=pd.read_csv("example_train1.csv")
data.head()

Document      Class
0         Teclov is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [10]:
data['Class']=data['Class'].map({'education':1,'cinema':0})
data.head()

Document  Class
0         Teclov is a great educational institution.      1
1            Educational greatness depends on ethics      1
2  A story of great ethics and educational greatness      1
3                           Sholey is a great cinema      0
4                   good movie depends on good story      0

In [11]:
matrix=data.as_matrix()
print(matrix)

[['Teclov is a great educational institution.' 1]
 ['Educational greatness depends on ethics' 1]
 ['A story of great ethics and educational greatness' 1]
 ['Sholey is a great cinema' 0]
 ['good movie depends on good story' 0]]


In [15]:
X=matrix[:,0]
Y=matrix[:,1]
Y=Y.astype('int')
print(X)
print(Y)

['Teclov is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
[1 1 1 0 0]


In [22]:
from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer()
vec.fit(X)
print(vec.vocabulary_)

{'teclov': 15, 'is': 9, 'great': 6, 'educational': 3, 'institution': 8, 'greatness': 7, 'depends': 2, 'on': 12, 'ethics': 4, 'story': 14, 'of': 11, 'and': 0, 'sholey': 13, 'cinema': 1, 'good': 5, 'movie': 10}


In [23]:
vec=CountVectorizer(stop_words='english')
vec.fit(X)
print(vec.vocabulary_)

{'teclov': 11, 'great': 5, 'educational': 2, 'institution': 7, 'greatness': 6, 'depends': 1, 'ethics': 3, 'story': 10, 'sholey': 9, 'cinema': 0, 'good': 4, 'movie': 8}


In [25]:
X_transform=vec.transform(X)
print(X_transform)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [27]:
X=X_transform.toarray()
print(X)

[[0 0 1 0 0 1 0 1 0 0 0 1]
 [0 1 1 1 0 0 1 0 0 0 0 0]
 [0 0 1 1 0 1 1 0 0 0 1 0]
 [1 0 0 0 0 1 0 0 0 1 0 0]
 [0 1 0 0 2 0 0 0 1 0 1 0]]


In [29]:
pd.DataFrame(X,columns=vec.get_feature_names())

cinema  depends  educational  ethics  good  great  greatness  institution  \
0       0        0            1       0     0      1          0            1   
1       0        1            1       1     0      0          1            0   
2       0        0            1       1     0      1          1            0   
3       1        0            0       0     0      1          0            0   
4       0        1            0       0     2      0          0            0   

   movie  sholey  story  teclov  
0      0       0      0       1  
1      0       0      0       0  
2      0       0      1       0  
3      0       1      0       0  
4      1       0      1       0

In [30]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(X,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)